---
- name: Configure KnoxMakers Debian 13 laptops
  hosts: knoxmakers_laptops
  gather_facts: true

  pre_tasks:
    - name: Refresh apt cache (valid 1 day)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  tasks:
    - name: Ensure base packages are installed
      ansible.builtin.apt:
        name: "{{ common_packages }}"
        state: present

    - name: Ensure laptop-specific packages are installed
      vars:
        laptop_packages: []  # set your laptop-only package list here
      ansible.builtin.apt:
        name: "{{ laptop_packages }}"
        state: present
      when: (laptop_packages | default([])) | length > 0

    - name: Ensure shared knoxmakers user exists with sudo access  # shared login on public laptops
      ansible.builtin.user:
        name: "{{ knoxmakers_username }}"
        password: "{{ knoxmakers_password_hash }}"
        shell: /bin/bash
        groups: sudo
        append: true
        state: present
        create_home: true

    - name: Deploy AppImages
      ansible.builtin.import_tasks: tasks/appimages.yml
      vars:
        appimages: []
        # Example:
        # appimages:
        #   - name: audacity
        #     filename: audacity-3.5.0-x86_64.AppImage
        #     icon: icon.png
        #     desktop_name: Audacity
        #     desktop_id: audacity
        #     categories: AudioVideo;Audio;

    - name: Ensure Flathub remote is configured for Flatpak
      ansible.builtin.command:
        cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      register: flathub_remote
      changed_when: "'already exists' not in (flathub_remote.stdout + flathub_remote.stderr)"

    - name: Set system timezone
      ansible.builtin.timezone:
        name: "{{ timezone }}"

    - name: Verify connectivity
      ansible.builtin.ping:
        data: "knoxmakers laptops ready"
